### ISSUE TITLE
Regex Tool 2024.4.1 errors out repeatedly

### ISSUE THREAD

**Issue by tkirkland** [kookob/plugin#20]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'G' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.obroom.plugin.regextool]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by kookob** [comment]
Version compatibility problem, please wait for the new version to fix, thank you for your feedback.

**Comment by tkirkland** [comment]
Thanks for the heads up.

**Comment by kookob** [comment]
The latest version is now available: https://plugins.jetbrains.com/plugin/15433-regex-tool
