### ISSUE TITLE
Code Radio in Webstorm crash

### ISSUE THREAD

**Issue by pronovaso** [kookob/plugin#24]
Hi.
In last Webstorm 2024.1.5 plugin crash after start the IDE or enable.Can you with fix add support for 2024.2?

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.obroom.plugin.coderadio.action.PlayAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.obroom.plugin.coderadiolite]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

Thanks

**Comment by kookob** [comment]
The new version has been submitted for review.
But you can download and use them in advance.
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=580690
This is a niche plugin with few users.
Thank you for your support.
