### ISSUE TITLE
Can not work

### ISSUE THREAD

**Issue by IdealBoy709** [kookob/plugin#29]
om.intellij.diagnostic.PluginException: Cannot init toolwindow toolset.bc@58514abf [Plugin: com.obroom.plugin.toolset]
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:234)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invokeSuspend(ToolWindowSetInitializer.kt:141)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:53)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:48)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

**Comment by kookob** [comment]
Which IDE and which version?
Which toolset plugin version?

**Comment by IdealBoy709** [comment]
Located in webstorm (2024.3)
The plugin version is 2024.8.1

**Comment by IdealBoy709** [comment]
Caused by: java.lang.ClassNotFoundException: com.intellij.json.JsonLanguage PluginClassLoader(plugin=PluginDescriptor(name=Toolset, id=com.obroom.plugin.toolset, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2024.3/plugins/toolset, version=2024.8.1, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/Applications/WebStorm.app/Contents/lib, version=243.21565.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/Applications/WebStorm.app/Contents/lib, version=243.21565.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/Applications/WebStorm.app/Contents/lib, version=243.21565.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/Applications/WebStorm.app/Contents/lib, version=243.21565.180, package=null, isBundled=true), )

**Comment by kookob** [comment]
Please try updating to the latest version. Thank you.
